### PR TITLE
Embedded video player

### PR DESCRIPTION
**Pull request by biolds**
This PR adds an embedded video player and a download link to videos in the media view.

1st commit fixes the handling of Django's FileField (see https://docs.djangoproject.com/en/4.1/topics/files/)
2nd commit uses Nginx X-Accel-Redirect feature to offload the video streaming (see https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/#x-accel-redirect)

### CODE REVIEW

**Comment by meeb** [comment]
Thanks for the PR! This looks like an excellent addition and thanks for keeping it in the same code style.

**Comment by biolds** [comment]
Thanks for this great project and the fast merging ! :)

**Comment by meeb** [comment]
No problem. A bunch of stuff is in the slightly older Django way of doing things now so feel free to poke about if you like. This PR probably won't get released until I can fully test it as well as fix the container build so it might be a few days.

**Comment by biolds** [comment]
No worries for a release, I'm running a dev version. Let me know if know if you find issues.

**Pull request merged**
