### PR TITLE
Add support for indexing Streams

### PR DESCRIPTION
**Pull request by FaySmash**
Tweaked the original code a little and added option to only index streams.

### CODE REVIEW

**Comment by meeb** [comment]
Thanks! Looks reasonable. I'll give it a test shortly.

**Comment by FaySmash** [comment]
Here
```
BooleanField(
        _('index videos'),
        default=False
```
the default should be set to `True` to keep the current behavior, an oversight.

**Comment by FaySmash** [comment]
quick update: 90% of them are streams, still no issues

dls

**Comment by meeb** [comment]
Thanks for the update. This has also been working fine for me in testing.

**Pull request merged**
