### PR TITLE
Improve skip filtering with regex invert and duration limits

### LINKED ISSUE #482: Thumbnails downloading for videos older than download cap
I have YouTube sources added which contain thousands of videos. However, I only care about new videos, as I'm transitioning away from direct YouTube viewing, so I have the Download Cap set to 1 week for each source. I only care about videos from the last week, and new ones as they arrive.

However, TubeSync is still downloading thumbnails for EVERY video in each source. Looking at the queued tasks, there are thousands of tasks waiting to download very old thumbnails. It can take several hours for it to work through those and get to the actual videos. This also causes the database file to get very large.

Is this intended behavior, or can it be changed to entirely ignore downloads of content older than the download cap?

### PR DESCRIPTION
**Pull request by timwhite**
Fix #482, #266

- Allow filtering based on duration (either with a minimum or maximum duration)
- Allow filtering on regex and inverted regex (easier than lookahead regex's)
- Cleanup of all filtering code into single location (triggered on Media save)
- Bring title and duration into own fields in DB to allow filtering quickly without looking up metadata
- Update derived database fields from metadata on save

Source edit view
Screenshot from 2024-07-13 08-32-17

Source view (with inverted regex)
Screenshot from 2024-07-13 08-32-59

### CODE REVIEW

**Comment by meeb** [comment]
This looks excellent, many thanks for the PR! I'll give your commits a once-over shortly.

**Comment by meeb** [comment]
Zero issues obvious with your commits, nicely done. I'll merge it, give it a test and bundle it into the next release.

**Comment by timwhite** [comment]
@meeb thanks. Happy to have had some time to contribute back. I have a QOL PR coming shortly, and also a way to solve #509 to think about

**Comment by meeb** [comment]
@timwhite there might have been a couple of minor issues introduced with your filtering refactoring and issues with silly long titles. Feel free to review my two hot fix commits above (https://github.com/meeb/tubesync/commit/69a824e33403143f1289608dc37717c1dd62fded for #518 and https://github.com/meeb/tubesync/commit/68de80748344ea51eadb6320fcc3706cb65b2aaa for #519) if you get a moment.

**Comment by timwhite** [comment]
@meeb those commits look good. I can see how the date bug came in. Interesting about the title length issue. All my googling said the maximum length was 100 characters. (e.g. https://developers.google.com/youtube/v3/docs/videos). I wonder if it's a utf encoding thing, but my understanding was that it was 100 utf characters, which is what the database was setup with. Your fixes look perfect.

**Comment by meeb** [comment]
I'm pretty sure SQLite uses character counters and not byte counters so it's probably not that:

```sql
sqlite> select length('😀');
1
```

It's probably just YouTube returning massive titles. Either way, not a complex fix!

**Pull request merged**
