### PR TITLE
Ignore case when checking the filter

### PR DESCRIPTION
**Pull request by RichardHyde**
Make the checks against the sources filter text case insensitive.

### CODE REVIEW

**Review by tcely — COMMENTED** [review]
Making the matching in filtering case-insensitive actually closes off options. It's already possible to match both cases.

**Comment by RichardHyde** [comment]
OK, it caught me out not realising that the filter was case-sensitive, so I thought it was worth a try 😀

**Comment by tcely** [comment]
I predict a new issue is forthcoming about how this breaks someone's filtering that is currently depending on case differences. 😉

**Comment by meeb** [comment]
Huh, I didn't mean to merge this for now. I had all the PRs open in different tabs and specifically didn't merge this. Maybe I've accidentality found a minor CSRF issue with GitHub... I'll undo it for now with a comment.

**Pull request merged**
