### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by biolds**

### CODE REVIEW

**Comment by biolds** [comment]
I've moved the commit to a separate PR, https://github.com/meeb/tubesync/pull/306

**Comment by meeb** [comment]
Nice, thanks. Can you confirm `make test` to run the tests works for you with this patch set? The automated tests are failing.

**Comment by biolds** [comment]
Yes, I'll have a look at it this evening, looks like it's not trivial.

**Comment by biolds** [comment]
Fixed

**Comment by meeb** [comment]
Looks good, thanks!

**Pull request merged**
